#  docker-compose -p ecom-monitor -f docker-compose-dev.yml up
version: '3.2'

networks:
   nest-app-network:
      driver: bridge

services:
   # mysql:
   #    image: mysql:8.0
   #    container_name: mysql-container
   #    volumes:
   #       - ./environments/mysql:/var/lib/mysql
   #    command: [
   #          '--character-set-server=utf8mb4',
   #          '--collation-server=utf8mb4_unicode_ci',
   #          '--skip-character-set-client-handshake', # Buộc tất cả kết nối sử dụng utf8mb4
   #       ]
   #    environment:
   #       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   #       MYSQL_DATABASE: ${DB_DATABASE}
   #       MYSQL_PASSWORD: ${DB_PASSWORD}
   #    ports:
   #       - '8811:3306'
   #    networks:
   #       - nest-app-network

   redis:
      container_name: pre-event-redis
      image: redis:latest
      ports:
         - '6319:6379'
      networks:
         - nest-app-network

   prometheus:
      image: prom/prometheus:latest
      container_name: pre-event-prometheus
      restart: unless-stopped
      volumes:
         - ./environments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
         - ./environments/data/prometheus_data:/prometheus
      command:
         - '--config.file=/etc/prometheus/prometheus.yml'
         - '--storage.tsdb.path=/prometheus'
         - '--web.console.libraries=/etc/prometheus/console_libraries'
         - '--web.console.templates=/etc/prometheus/consoles'
         - '--web.enable-lifecycle'
      extra_hosts:
         - host.docker.internal:host-gateway
      ports:
         - '9090:9090'
      networks:
         - nest-app-network

   grafana:
      image: grafana/grafana
      container_name: pre-event-grafana
      hostname: grafana
      environment:
         - GF_SECURITY_ADMIN_PASSWORD=admin
         - GF_USERS_ALLOW_SING_UP=false
         - GF_SERVER_DOMAIN=localhost
         #enable logger
         - GF_LOG_MODE=console file
         - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug
      volumes:
         - ./environments/data/grafana-storage:/var/lib/grafana
      ports:
         - '3000:3000'
      networks:
         - nest-app-network

   node-exporter:
      image: prom/node-exporter:latest
      container_name: pre-event-node-exporter
      restart: unless-stopped
      volumes:
         - /proc:/host/proc:ro
         - /sys:/host/sys:ro
         - /:/rootfs:ro
      command:
         - --path.procfs=/host/proc
         - --path.rootfs=/rootfs
         - --path.sysfs=/host/sys
         - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
      ports:
         - '9100:9100'
      networks:
         - nest-app-network

   mysqld-exporter:
      image: prom/mysqld-exporter
      container_name: pre-event-mysqld-exporter
      ports:
         - '9104:9104'
      command:
         - '--collect.engine_innodb_status'
         - '--collect.info_schema.processlist'
         - '--collect.info_schema.tables'
         - '--collect.info_schema.query_response_time'
         - '--collect.perf_schema.file_events'
         - '--collect.perf_schema.eventsstatements'
         - '--collect.perf_schema.indexiowaits'
         - '--collect.global_status'
         #      - '--ignore-tables' # Ko giám sát các table của hệ thống
         - '--config.my-cnf=/etc/mysql/.my.cnf'
      volumes:
         - ./environments/mysqld-exporter/.my.cnf:/etc/mysql/.my.cnf
      environment:
         - DATA_SOURCE_NAME=root:thailq@tcp(mysql:8811)/
      # depends_on:
      #    - mysql
      networks:
         - nest-app-network

   redis-exporter:
      image: oliver006/redis_exporter
      command: -redis.addr redis://redis:6319
      ports:
         - 9121:9121
      networks:
         - nest-app-network
