global:
   scrape_interval: 15s

scrape_configs:
   - job_name: 'ecommerce-prometheus'
     scrape_interval: 5s
     static_configs:
        - targets: ['host.docker.internal:9090']
     metrics_path: '/metrics'

   - job_name: 'ecommerce-nestjs'
     scrape_interval: 5s
     static_configs:
        - targets: ['host.docker.internal:3005']
     metrics_path: '/metrics'

   - job_name: 'ecommerce-node-exporter'
     scrape_interval: 5s
     static_configs:
        - targets: ['host.docker.internal:9100']

   - job_name: 'ecommerce-mysqld-exporter'
     scrape_interval: 5s
     static_configs:
        - targets: ['host.docker.internal:9104']
     metrics_path: '/metrics'
